export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './chatController.service';
import { ChatControllerService } from './chatController.service';
export * from './clinicalExaminationController.service';
import { ClinicalExaminationControllerService } from './clinicalExaminationController.service';
export * from './emailNotificationController.service';
import { EmailNotificationControllerService } from './emailNotificationController.service';
export * from './fileController.service';
import { FileControllerService } from './fileController.service';
export * from './identificationsController.service';
import { IdentificationsControllerService } from './identificationsController.service';
export * from './noteController.service';
import { NoteControllerService } from './noteController.service';
export * from './petsController.service';
import { PetsControllerService } from './petsController.service';
export * from './usersController.service';
import { UsersControllerService } from './usersController.service';
export * from './vaccinationsController.service';
import { VaccinationsControllerService } from './vaccinationsController.service';
export const APIS = [AuthControllerService, ChatControllerService, ClinicalExaminationControllerService, EmailNotificationControllerService, FileControllerService, IdentificationsControllerService, NoteControllerService, PetsControllerService, UsersControllerService, VaccinationsControllerService];
