/**
 * pet-passport
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatDto } from './chatDto';
import { Paging } from './paging';


export interface PageDtoChatDto { 
    content?: Array<ChatDto>;
    paging?: Paging;
    pageSize?: number;
    pageNumber?: number;
}

