/**
 * pet-passport
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PetCreateUpdateDto { 
    name: string;
    breed: string;
    sex: string;
    type: PetCreateUpdateDto.TypeEnum;
    avatarUri?: string;
    dateOfBirth: string;
    coat?: string;
    coatVariety?: string;
}
export namespace PetCreateUpdateDto {
    export type TypeEnum = 'DOG' | 'CAT' | 'PARROTS' | 'HAMSTER' | 'SNAKE';
    export const TypeEnum = {
        Dog: 'DOG' as TypeEnum,
        Cat: 'CAT' as TypeEnum,
        Parrots: 'PARROTS' as TypeEnum,
        Hamster: 'HAMSTER' as TypeEnum,
        Snake: 'SNAKE' as TypeEnum
    };
}


