/**
 * pet-passport
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserShortDto } from './userShortDto';


export interface PetDto { 
    id?: string;
    type?: PetDto.TypeEnum;
    avatarUri?: string;
    users?: Array<UserShortDto>;
    name?: string;
    breed?: string;
    sex?: string;
    dateOfBirth?: string;
    coat?: string;
    coatVariety?: string;
    createdAt?: string;
    updateAt?: string;
}
export namespace PetDto {
    export type TypeEnum = 'DOG' | 'CAT' | 'PARROTS' | 'HAMSTER' | 'SNAKE';
    export const TypeEnum = {
        Dog: 'DOG' as TypeEnum,
        Cat: 'CAT' as TypeEnum,
        Parrots: 'PARROTS' as TypeEnum,
        Hamster: 'HAMSTER' as TypeEnum,
        Snake: 'SNAKE' as TypeEnum
    };
}


