/**
 * pet-passport
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserServiceCreateUpdateDto { 
    petType?: UserServiceCreateUpdateDto.PetTypeEnum;
    serviceType?: string;
    message?: string;
    departure?: boolean;
    priceFixed?: number;
    priceMin?: number;
    priceMax?: number;
}
export namespace UserServiceCreateUpdateDto {
    export type PetTypeEnum = 'DOG' | 'CAT' | 'PARROTS' | 'HAMSTER' | 'SNAKE';
    export const PetTypeEnum = {
        Dog: 'DOG' as PetTypeEnum,
        Cat: 'CAT' as PetTypeEnum,
        Parrots: 'PARROTS' as PetTypeEnum,
        Hamster: 'HAMSTER' as PetTypeEnum,
        Snake: 'SNAKE' as PetTypeEnum
    };
}


