/**
 * pet-passport
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VaccinationDto { 
    id?: string;
    petId?: string;
    type?: string;
    name?: string;
    manufacturer?: string;
    batchNumber?: string;
    manufacturedAt?: string;
    bestBeforeAt?: string;
    vaccinationAt?: string;
    vaccinationUntilBeforeAt?: string;
    authorisedVeterinarian?: string;
    createdAt?: string;
    updateAt?: string;
}

